/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pokedex;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Poke extends javax.swing.JFrame {

    /**
     * Creates new form Poke
     */
    public Poke() {
        initComponents();
    }
    public static ArrayList <Pokemon> poke = new ArrayList();
    public static ArrayList <Peleas> enemigo = new ArrayList();
    public static Tienda t = new Tienda();
    public static Random xd = new Random();
    public int num;
    public int vidamax; 
    public int vidaene;
    public int oro;
    public int niv; 
    public int curacion;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Registrar = new javax.swing.JButton();
        Entrenar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        PELEA = new javax.swing.JButton();
        stats = new javax.swing.JButton();
        Tienda = new javax.swing.JButton();
        Inventario = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PokeTab = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        Charmander = new javax.swing.JButton();
        Squirtle = new javax.swing.JButton();
        Bulba = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lucha = new javax.swing.JTextArea();
        Curar = new javax.swing.JButton();
        Ataque = new javax.swing.JButton();
        Huir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        comprarmejora = new javax.swing.JButton();
        comprarcuras = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fondot = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registrar.setBackground(new java.awt.Color(255, 204, 204));
        Registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Registrar.setForeground(new java.awt.Color(0, 0, 0));
        Registrar.setText("Seleccione su Pokemon");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, 40));

        Entrenar.setBackground(new java.awt.Color(255, 204, 204));
        Entrenar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Entrenar.setForeground(new java.awt.Color(0, 0, 0));
        Entrenar.setText("Mejorar Pokemon");
        Entrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrenarActionPerformed(evt);
            }
        });
        jPanel1.add(Entrenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 180, 40));

        Salir.setBackground(new java.awt.Color(255, 204, 204));
        Salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(0, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 170, 30));

        PELEA.setBackground(new java.awt.Color(255, 204, 204));
        PELEA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PELEA.setForeground(new java.awt.Color(0, 0, 0));
        PELEA.setText("Enfrentamiento ");
        PELEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PELEAActionPerformed(evt);
            }
        });
        jPanel1.add(PELEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 180, 40));

        stats.setBackground(new java.awt.Color(255, 204, 204));
        stats.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stats.setForeground(new java.awt.Color(0, 0, 0));
        stats.setText("Estadisticas ");
        stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsActionPerformed(evt);
            }
        });
        jPanel1.add(stats, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 180, 40));

        Tienda.setBackground(new java.awt.Color(255, 204, 204));
        Tienda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tienda.setForeground(new java.awt.Color(0, 0, 0));
        Tienda.setText("Comprar Objetos");
        Tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiendaActionPerformed(evt);
            }
        });
        jPanel1.add(Tienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 170, 40));

        Inventario.setBackground(new java.awt.Color(255, 204, 204));
        Inventario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Inventario.setForeground(new java.awt.Color(0, 0, 0));
        Inventario.setText("Inventario");
        Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioActionPerformed(evt);
            }
        });
        jPanel1.add(Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 150, 40));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/fondo2.jpg"))); // NOI18N
        jPanel1.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 240, 810));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Charmander.setBackground(new java.awt.Color(255, 51, 51));
        Charmander.setForeground(new java.awt.Color(255, 0, 0));
        Charmander.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/Charmander.png"))); // NOI18N
        Charmander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharmanderActionPerformed(evt);
            }
        });
        jPanel3.add(Charmander, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 110, 120));

        Squirtle.setBackground(new java.awt.Color(51, 255, 255));
        Squirtle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/Squirtle.png"))); // NOI18N
        Squirtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquirtleActionPerformed(evt);
            }
        });
        jPanel3.add(Squirtle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 100, -1));

        Bulba.setBackground(new java.awt.Color(102, 255, 51));
        Bulba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/Bulba.png"))); // NOI18N
        Bulba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulbaActionPerformed(evt);
            }
        });
        jPanel3.add(Bulba, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Selecciona  a tu Pokemon :D");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 530, 50));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Charmander");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 250, 40));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Squirtle");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Bulbasaur");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/fondo.png"))); // NOI18N
        Fondo1.setText("jLabel2");
        jPanel3.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 820));

        PokeTab.addTab("tab1", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lucha.setBackground(new java.awt.Color(153, 255, 255));
        Lucha.setColumns(20);
        Lucha.setRows(5);
        jScrollPane1.setViewportView(Lucha);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 710, 460));

        Curar.setBackground(new java.awt.Color(0, 255, 51));
        Curar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/Heal.png"))); // NOI18N
        Curar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurarActionPerformed(evt);
            }
        });
        jPanel4.add(Curar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 100, 90));

        Ataque.setBackground(new java.awt.Color(255, 0, 51));
        Ataque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/ataque.png"))); // NOI18N
        Ataque.setText("Ataque");
        Ataque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtaqueActionPerformed(evt);
            }
        });
        jPanel4.add(Ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 100, 90));

        Huir.setBackground(new java.awt.Color(255, 255, 0));
        Huir.setForeground(new java.awt.Color(255, 255, 51));
        Huir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/huir.png"))); // NOI18N
        Huir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuirActionPerformed(evt);
            }
        });
        jPanel4.add(Huir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 100, 90));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Ataque");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 0));
        jLabel6.setText("Curación ");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Escapar");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/fondo.png"))); // NOI18N
        Fondo2.setText("jLabel1");
        jPanel4.add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 850, 850));

        PokeTab.addTab("tab2", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comprarmejora.setBackground(new java.awt.Color(255, 255, 0));
        comprarmejora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/mejora.png"))); // NOI18N
        comprarmejora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarmejoraActionPerformed(evt);
            }
        });
        jPanel5.add(comprarmejora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 110, -1));

        comprarcuras.setBackground(new java.awt.Color(0, 255, 51));
        comprarcuras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/Heal.png"))); // NOI18N
        comprarcuras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarcurasActionPerformed(evt);
            }
        });
        jPanel5.add(comprarcuras, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, 130));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Bienvenido a la PokeTienda");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 520, 50));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Que desea comprar?");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Bayas de Mejora");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("MegaPocion");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("300 y");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("150 Y");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, -1, -1));

        fondot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/tienda..jpg"))); // NOI18N
        fondot.setText("jLabel8");
        jPanel5.add(fondot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 849, 750));

        PokeTab.addTab("tab3", jPanel5);

        jPanel2.add(PokeTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 840, 900));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/fondo.png"))); // NOI18N
        jPanel2.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed
    private void PELEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PELEAActionPerformed
      if(poke.isEmpty()){
      JOptionPane.showMessageDialog(null,"Elija su pokemon antes de pelear!"); 
      }else{
      PokeTab.setSelectedIndex(1);
      Lucha.append("Que comience la batalla!"); 
      Peleas e1 = snorlax();
      enemigo.add(e1);
      Peleas e2 =  ponyta();
      enemigo.add(e2);
      Peleas e3 = wooper();
      enemigo.add(e3);
      num = xd.nextInt(3);
      vidamax = poke.get(0).getVida();
      vidaene = enemigo.get(num).getVida();
      JOptionPane.showMessageDialog(null,"Pokemon Rival: "+  enemigo.get(num).getNombre());
      }
    }//GEN-LAST:event_PELEAActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        PokeTab.setSelectedIndex(0);
    }//GEN-LAST:event_RegistrarActionPerformed

    private void CharmanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharmanderActionPerformed
        poke.clear();
        int vida = 39;
        int ataque = 52;
        int def = 43;
        int vel = 65;
        String tipo = "Fuego";
        String n = "Charmander";
        Pokemon p = new Pokemon(vida,ataque,tipo,n,1,def,vel);
        poke.add(p);
        JOptionPane.showMessageDialog(null,"Ha seleccionado a Charmander");
    }//GEN-LAST:event_CharmanderActionPerformed

    private void statsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsActionPerformed
        String msj = "";
        if(poke.isEmpty()){
            msj = "No ha seleccionado ningun pokemon";
        }else{msj = "Pokemon: "+poke.get(0).getNombre()+"\nVida: "+poke.get(0).getVida()+"   Nivel: "+poke.get(0).getNivel() +"\nAtaque: "+poke.get(0).getAtaque()+"\nDefensa: "+poke.get(0).getDefensa()+"\nVelocidad: "+poke.get(0).getVelocidad()+"\nTipo: "+poke.get(0).getTipo();}
        
        JOptionPane.showMessageDialog(null,msj);
    }//GEN-LAST:event_statsActionPerformed

    private void BulbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulbaActionPerformed
        poke.clear();
        int vida = 45;
        int ataque = 49;
        int def = 49;
        int vel = 45;
        String tipo = "Planta";
        String nombre = "Bulbasaur";
        Pokemon p = new Pokemon(vida,ataque,tipo,nombre,1,def,vel);
        poke.add(p);
        JOptionPane.showMessageDialog(null,"Ha seleccionado a Bulbasaur");
    }//GEN-LAST:event_BulbaActionPerformed

    private void SquirtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquirtleActionPerformed
        poke.clear();
        int vida = 44;
        int ataque = 48;
        int def = 65;
        int vel = 43;
        String tipo = "Agua";
        String nombre = "Squirtle";
        Pokemon p = new Pokemon(vida,ataque,tipo,nombre,1,def,vel);
        poke.add(p);
        JOptionPane.showMessageDialog(null,"Ha seleccionado a Squirtle");
    }//GEN-LAST:event_SquirtleActionPerformed

    private void EntrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrenarActionPerformed
       int num = xd.nextInt(9,21);
       if(t.getMejora()<5){
           JOptionPane.showMessageDialog(null,"Bayas Pokemon Insuficientes");
       }else{
           int resta = t.getMejora()-5;
           int vida = poke.get(0).getVida()+num;
           int ataque = poke.get(0).getAtaque()+num;
           int vel = poke.get(0).getVelocidad()+num;
           int def = poke.get(0).getDefensa()+num;
           int nivel = poke.get(0).getNivel()+1;
           poke.get(0).setVida(vida);
           poke.get(0).setAtaque(ataque);
           poke.get(0).setVelocidad(vel);
           poke.get(0).setDefensa(def);
           poke.get(0).setNivel(nivel);
           t.setMejora(resta);
           String msj = "Pokemon: "+poke.get(0).getNombre()+"\nVida: "+poke.get(0).getVida()+"   Nivel: "+poke.get(0).getNivel() +"\nAtaque: "+poke.get(0).getAtaque()+"\nDefensa: "+poke.get(0).getDefensa()+"\nVelocidad: "+poke.get(0).getVelocidad()+"\nTipo: "+poke.get(0).getTipo();
           JOptionPane.showMessageDialog(null,msj);
       }
    }//GEN-LAST:event_EntrenarActionPerformed

    private void HuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuirActionPerformed
       JOptionPane.showMessageDialog(null,"En serio crees que puedes huir? No seas cobarde");
    }//GEN-LAST:event_HuirActionPerformed

    private void CurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurarActionPerformed
        int x = t.getCuracion();
        int vida = poke.get(0).getVida();
        if(t.getCuracion() > 0 && vidamax > poke.get(0).getVida()){
         int c = 50;
         vida += c;
         if(vidamax<vida){
             vida = vidamax;
         }
         poke.get(0).setVida(vida);   
         int resta = x--;
         t.setCuracion(resta);
          JOptionPane.showMessageDialog(null,"Curacion Realizada! PS: "+poke.get(0).getVida());  
       }else if(x == 0){
         JOptionPane.showMessageDialog(null,"Se han agotado tus pociones :c ");  
       }
       else{
           JOptionPane.showMessageDialog(null,"Puntos de Salud maximos!");
       }
    }//GEN-LAST:event_CurarActionPerformed

    private void AtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtaqueActionPerformed
       
       int cantidad;
       int cantidad2;
       if(poke.isEmpty()){
          JOptionPane.showMessageDialog(null,"Elija su pokemon antes de pelear!");  
       }else{
       if(!poke.get(0).isFainted() && !enemigo.get(num).isFainted()){
           if(poke.get(0).getVelocidad() > enemigo.get(num).getVelocidad()){
               attack(enemigo, num);
               if(!enemigo.get(num).isFainted()){
                   attack2(poke,num);
               }
           }
           else{
               attack2(poke,num);
               if(!poke.get(0).isFainted()){
                   attack(enemigo,num);
               }
           }
          Lucha.append(poke.get(0).getNombre()+" Vida: " +poke.get(0).getVida());
          Lucha.append(enemigo.get(num).getNombre()+" Vida: " +enemigo.get(num).getVida());
           }
                if(poke.get(0).isFainted()){
               JOptionPane.showMessageDialog(null,poke.get(0).getNombre()+" Ha sido derrotado!");
               poke.get(0).setVida(vidamax);
               enemigo.get(num).setVida(vidaene);
               Lucha.setText("");
       }else if(enemigo.get(num).isFainted()){
                 JOptionPane.showMessageDialog(null,enemigo.get(num).getNombre()+" Ha sido derrotado!");    
                 Lucha.setText("");
                 poke.get(0).setVida(vidamax);
                 enemigo.get(num).setVida(vidaene);
                 
                 int aleatorio = xd.nextInt(2);
                 switch(aleatorio){
                     case 0:
                       oro = 300;
                       niv = 1;
                         break;
                         
                     case 1:
                         oro = 500;
                       niv = 0;
                         break;
                 }
                 cantidad = t.getOro()+oro;
                 cantidad2 = t.getMejora()+niv;
                 t.setOro(cantidad);
                 t.setMejora(cantidad2);
                }
       }
    }//GEN-LAST:event_AtaqueActionPerformed

    private void TiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiendaActionPerformed
       PokeTab.setSelectedIndex(2); 
    }//GEN-LAST:event_TiendaActionPerformed

    private void comprarmejoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarmejoraActionPerformed
        if(t.getOro()<150){
            JOptionPane.showMessageDialog(null,"Dinero Insuficiente");    
        }else{
            niv++;
            int resta =  t.getOro()-150;
            t.setOro(resta);
            t.setMejora(niv);
            JOptionPane.showMessageDialog(null,"Gracias por su PokeCompra"+"\nRevise su Inventario");  
        }
        
    }//GEN-LAST:event_comprarmejoraActionPerformed

    private void comprarcurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarcurasActionPerformed
        if(t.getOro()<300){
            JOptionPane.showMessageDialog(null,"Dinero Insuficiente");    
        }else{
            curacion++;
            int resta =  t.getOro()-300;
            t.setOro(resta);
            t.setCuracion(curacion);
            JOptionPane.showMessageDialog(null,"Gracias por su PokeCompra"+"\nRevise su Inventario");  
        }
    }//GEN-LAST:event_comprarcurasActionPerformed

    private void InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioActionPerformed
         JOptionPane.showMessageDialog(null,"Inventario"+"\nOro: "+t.getOro()+"\nBayas de mejora: "+t.getMejora()+"\nPociones de curacion: "+t.getCuracion());  
    }//GEN-LAST:event_InventarioActionPerformed
  public void attack(ArrayList <Peleas> opponent, int num) {
        int damage = (poke.get(0).getAtaque() - enemigo.get(num).getDefensa()) + xd.nextInt(10 , 20); // Daño con un pequeño elemento aleatorio
        if (damage < 0) damage = 1; // Asegurarse de que el daño mínimo sea 1
        Lucha.append("\n  "+poke.get(0).getNombre()+ " ataca a " + enemigo.get(num).getNombre() + " y causa " + damage + " puntos de daño.");
        int vida = enemigo.get(num).getVida() - damage;
        enemigo.get(num).setVida(vida);
    }
  
  public void attack2 (ArrayList <Pokemon> opponent, int num) {
        int damage = (enemigo.get(num).getAtaque() - poke.get(0).getDefensa()) + xd.nextInt(10 , 20); 
        if (damage < 0) damage = 1; 
        Lucha.append("\n  "+enemigo.get(num).getNombre()+ " ataca a " + poke.get(0).getNombre() + " y causa " + damage + " puntos de daño.");
        int vida = poke.get(0).getVida() - damage;
        poke.get(0).setVida(vida);
    }
  public Peleas snorlax(){
         int vida = 160;
        int ataque = 110;
        int def = 65;
        int vel = 35;
        String tipo = "Normal";
        String nombre = "Snorlax";
        Peleas p = new Peleas(vida,ataque,tipo,nombre,def,vel);
        return p;
  }
  public Peleas ponyta(){
         int vida = 50;
        int ataque = 45;
        int def = 55;
        int vel = 90;
        String tipo = "Fuego";
        String nombre = "Ponyta";
        Peleas p = new Peleas(vida,ataque,tipo,nombre,def,vel);
        return p;
  }
  public Peleas wooper(){
         int vida = 55;
        int ataque = 45;
        int def = 45;
        int vel = 15;
        String tipo = "Agua";
        String nombre = "Wooper";
        Peleas p = new Peleas(vida,ataque,tipo,nombre,def,vel);
        return p;
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Poke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Poke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Poke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Poke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Poke().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ataque;
    private javax.swing.JButton Bulba;
    private javax.swing.JButton Charmander;
    private javax.swing.JButton Curar;
    private javax.swing.JButton Entrenar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JButton Huir;
    private javax.swing.JButton Inventario;
    private javax.swing.JTextArea Lucha;
    private javax.swing.JButton PELEA;
    private javax.swing.JTabbedPane PokeTab;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Squirtle;
    private javax.swing.JButton Tienda;
    private javax.swing.JButton comprarcuras;
    private javax.swing.JButton comprarmejora;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton stats;
    // End of variables declaration//GEN-END:variables
}
