/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pokedex;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Poke extends javax.swing.JFrame {

    /**
     * Creates new form Poke
     */
    public Poke() {
        initComponents();
    }
    public static ArrayList <Pokemon> poke = new ArrayList();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Registrar = new javax.swing.JButton();
        Entrenar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        PELEA = new javax.swing.JButton();
        stats = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();
        Entrenar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PokeTab = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        Charmander = new javax.swing.JButton();
        Squirtle = new javax.swing.JButton();
        Bulba = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Fondo2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registrar.setBackground(new java.awt.Color(255, 204, 204));
        Registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Registrar.setForeground(new java.awt.Color(0, 0, 0));
        Registrar.setText("Seleccione su Pokemon");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 200, 40));

        Entrenar.setBackground(new java.awt.Color(255, 204, 204));
        Entrenar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Entrenar.setForeground(new java.awt.Color(0, 0, 0));
        Entrenar.setText("Entrenar Pokemon");
        jPanel1.add(Entrenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 180, 40));

        Salir.setBackground(new java.awt.Color(255, 204, 204));
        Salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(0, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 170, 30));

        PELEA.setBackground(new java.awt.Color(255, 204, 204));
        PELEA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PELEA.setForeground(new java.awt.Color(0, 0, 0));
        PELEA.setText("Enfrentamiento ");
        PELEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PELEAActionPerformed(evt);
            }
        });
        jPanel1.add(PELEA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 180, 40));

        stats.setBackground(new java.awt.Color(255, 204, 204));
        stats.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stats.setForeground(new java.awt.Color(0, 0, 0));
        stats.setText("Estadisticas ");
        stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsActionPerformed(evt);
            }
        });
        jPanel1.add(stats, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 180, 40));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/fondo2.jpg"))); // NOI18N
        jPanel1.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 240, 865));

        Entrenar1.setBackground(new java.awt.Color(255, 204, 204));
        Entrenar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Entrenar1.setForeground(new java.awt.Color(0, 0, 0));
        Entrenar1.setText("Entrenar Pokemon");
        jPanel1.add(Entrenar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 180, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Charmander.setBackground(new java.awt.Color(255, 51, 51));
        Charmander.setForeground(new java.awt.Color(255, 0, 0));
        Charmander.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/Charmander.png"))); // NOI18N
        Charmander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharmanderActionPerformed(evt);
            }
        });
        jPanel3.add(Charmander, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 110, 120));

        Squirtle.setBackground(new java.awt.Color(51, 255, 255));
        Squirtle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/Squirtle.png"))); // NOI18N
        Squirtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquirtleActionPerformed(evt);
            }
        });
        jPanel3.add(Squirtle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 100, -1));

        Bulba.setBackground(new java.awt.Color(102, 255, 51));
        Bulba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/Bulba.png"))); // NOI18N
        Bulba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulbaActionPerformed(evt);
            }
        });
        jPanel3.add(Bulba, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Selecciona  a tu Pokemon :D");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 530, 50));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Charmander");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 250, 40));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Squirtle");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Bulbasaur");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/fondo.png"))); // NOI18N
        Fondo1.setText("jLabel2");
        jPanel3.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 834, 820));

        PokeTab.addTab("tab1", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/fondo.png"))); // NOI18N
        Fondo2.setText("jLabel1");
        jPanel4.add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -1, 850, 820));

        PokeTab.addTab("tab2", jPanel4);

        jPanel2.add(PokeTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 840, 900));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokedex/fondo.png"))); // NOI18N
        jPanel2.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void PELEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PELEAActionPerformed
      PokeTab.setSelectedIndex(1);
    }//GEN-LAST:event_PELEAActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        PokeTab.setSelectedIndex(0);
    }//GEN-LAST:event_RegistrarActionPerformed

    private void CharmanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharmanderActionPerformed
        poke.clear();
        int vida = 39;
        int ataque = 52;
        String tipo = "Fuego";
        String n = "Charmander";
        Pokemon p = new Pokemon(vida,ataque,tipo,n);
        poke.add(p);
        JOptionPane.showMessageDialog(null,"Ha seleccionado a Charmander");
    }//GEN-LAST:event_CharmanderActionPerformed

    private void statsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsActionPerformed
        String msj = "";
        if(poke.isEmpty()){
            msj = "No ha seleccionado ningun pokemon";
        }else{msj = "Pokemon: "+poke.get(0).getNombre()+"\nVida: "+poke.get(0).getVida()+"\nAtaque: "+poke.get(0).getAtaque()+"\nTipo: "+poke.get(0).getTipo();}
        
        JOptionPane.showMessageDialog(null,msj);
    }//GEN-LAST:event_statsActionPerformed

    private void BulbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulbaActionPerformed
        poke.clear();
        int vida = 45;
        int ataque = 49;
        String tipo = "Planta";
        String nombre = "Bulbasaur";
        Pokemon p = new Pokemon(vida,ataque,tipo,nombre);
        poke.add(p);
        JOptionPane.showMessageDialog(null,"Ha seleccionado a Bulbasaur");
    }//GEN-LAST:event_BulbaActionPerformed

    private void SquirtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquirtleActionPerformed
        poke.clear();
        int vida = 44;
        int ataque = 48;
        String tipo = "Agua";
        String nombre = "Squirtle";
        Pokemon p = new Pokemon(vida,ataque,tipo,nombre);
        poke.add(p);
        JOptionPane.showMessageDialog(null,"Ha seleccionado a Squirtle");
    }//GEN-LAST:event_SquirtleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Poke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Poke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Poke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Poke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Poke().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bulba;
    private javax.swing.JButton Charmander;
    private javax.swing.JButton Entrenar;
    private javax.swing.JButton Entrenar1;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JButton PELEA;
    private javax.swing.JTabbedPane PokeTab;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Squirtle;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton stats;
    // End of variables declaration//GEN-END:variables
}
